# Generated by Django 2.0.2 on 2018-03-06 04:41

import accounts.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0002_auto_20180221_0653'),
    ]

    operations = [
        migrations.AddField(
            model_name='useraccount',
            name='aboutMe',
            field=models.CharField(blank=True, default='', max_length=300),
        ),
        migrations.AlterField(
            model_name='useraccount',
            name='profilePic',
            field=models.ImageField(blank=True, null=True, upload_to=accounts.models.UploadToPathAndRename('images')),
        ),
    ]
