# Generated by Django 2.0.2 on 2018-03-06 04:54

import annoying.fields
from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0003_auto_20180306_0441'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='useraccount',
            name='id',
        ),
        migrations.AddField(
            model_name='useraccount',
            name='pkk',
            field=models.IntegerField(default=-1, editable=False),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='useraccount',
            name='user',
            field=annoying.fields.AutoOneToOneField(on_delete=django.db.models.deletion.CASCADE, primary_key=True, related_name='profInfo', serialize=False, to=settings.AUTH_USER_MODEL),
        ),
    ]
