# Generated by Django 2.0.2 on 2018-03-05 01:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('recipies', '0005_auto_20180227_0426'),
    ]

    operations = [
        migrations.AddField(
            model_name='recipe',
            name='like_id',
            field=models.CharField(default='l', editable=False, max_length=20),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='recipe',
            name='save_id',
            field=models.CharField(default='s', editable=False, max_length=20),
            preserve_default=False,
        ),
    ]
