# Generated by Django 2.0.2 on 2018-03-06 04:41

from django.db import migrations, models
import recipies.models


class Migration(migrations.Migration):

    dependencies = [
        ('recipies', '0007_auto_20180305_0259'),
    ]

    operations = [
        migrations.AlterField(
            model_name='recipe',
            name='pic',
            field=models.ImageField(blank=True, null=True, upload_to=recipies.models.UploadToPathAndRename('images')),
        ),
    ]
